### ISSUE TITLE
Include "alien league" font.

### ISSUE THREAD

**Issue by FOSS-Love** [pawap90/space-commit#46]
As it is not a generic font people have on their system installed. It will be best to include.

**Comment by pawap90** [comment]
Definitely! There was an attempt at including it, but it's not working.

For context:
You can see the following code in `style.css` (starting on line 27): 

```css
.github-url a {
  font-family: "Alien League";   /* 👈 */
  text-decoration: none;
  color: white;
  font-size: 25px;
}

@font-face {
  font-family: "Alien League";
  src: local("./AlienLeagueIiGradientBold.otf"); /* 👈 */
}
```

Making some quick tests I noticed if I replaced `local("./AlienLeagueIiGradientBold.otf");` with `url("./AlienLeagueIiGradientBold.otf");` it worked for me. Maybe that's the fix? I'm not much of a CSS expert, tbh.
